In [16]:
grid = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]
       ]

In [88]:
import numpy as np
print (np.matrix(grid))

def is_possible(x, y, n):
    result = True
    line = grid[y]
    print('line - ', line)
    if n in line: 
        result = False

    column = [c[x] for c in grid]
    print('column - ', column)
    if n in column: 
        result = False
    
    bloc_size = 3
    bl_x = x//bloc_size
    bl_y = y//bloc_size

    print(bl_x, ' - ', bl_y)
    
    print(bl_x * 3, ' - ', bl_x * 3 + 3) 
    
    for z in grid[bl_x * 3: bl_x * 3 + 3 ]:
        print(z[bl_y * 3: bl_y * 3 + 3])
    
    return result

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [89]:
p = is_possible(6, 6, 5)
print(p)

line -  [0, 6, 0, 0, 0, 0, 2, 8, 0]
column -  [0, 0, 0, 0, 0, 0, 2, 0, 0]
2  -  2
6  -  9
[2, 8, 0]
[0, 0, 5]
[0, 7, 9]
True
